CREATE DATABASE netstore;
USE netstore;
CREATE TABLE categorys(
	id VARCHAR(100) PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	description VARCHAR(255)
);
CREATE TABLE books(
	id VARCHAR(100) PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	author VARCHAR(100),
	price FLOAT(8,2),
	path VARCHAR(100),
	photoFileName VARCHAR(100),
	description VARCHAR(255),
	categoryId VARCHAR(100),
	CONSTRAINT category_id_fk FOREIGN KEY(categoryId) REFERENCES categorys(ID)
);

CREATE TABLE customers(
	id VARCHAR(100) PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	phone VARCHAR(100) NOT NULL,
	address VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	actived BIT(1),
	code VARCHAR(100) NOT NULL UNIQUE
);